# debug: false
# no_logo: false
# no_start: false
# no_connect: false
# no_share_scan: false
# no_version_check: false
# remote_configuration: false
# instance_name: default
# directories:
#   incomplete: ~
#   downloads: ~
#   shared:
#     - ~
# global:
#   upload:
#     slots: 20
# filters:
#   share:
#     - \.ini$
#     - Thumbs.db$
#     - \.DS_Store$
# web:
#   port: 5000
#   https:
#     port: 5001
#     force: false
#     certificate:
#       pfx: ~
#       password: ~
#   url_base: /
#   content_path: wwwroot
#   logging: false
#   authentication:
#     disabled: false
#     username: slskd
#     password: slskd
#     jwt:
#       key: ~
#       ttl: 604800000
# logger:
#   loki: ~
# feature:
#   prometheus: false
#   swagger: false
# soulseek:
#   username: ~
#   password: ~
#   listen_port: 50000
#   diagnostic_level: Info
#   distributed_network:
#     disabled: false
#     disable_children: false
#     child_limit: 25
#   connection:
#     timeout:
#       connect: 10000
#       inactivity: 15000
#     buffer:
#       read: 16384
#       write: 16384
#       transfer: 262144
#       write_queue: 250
#     proxy:
#       enabled: false
#       address: ~
#       port: ~
#       username: ~
#       password: ~
# integration:
#   ftp:
#     enabled: false
#     address: ~
#     port: ~
#     username: ~
#     password: ~
#     remote_path: /
#     encryption_mode: auto
#     ignore_certificate_errors: false
#     overwrite_existing: true
#     connection_timeout: 5000
#     retry_attempts: 3
#   pushbullet:
#     enabled: false
#     access_token: ~
#     notification_prefix: "From slskd:"
#     notify_on_private_message: true
#     notify_on_room_mention: true
#     retry_attempts: 3
#     cooldown_time: 900000