# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["win-x64", "linux-x64"]
    steps:
      - uses: actions/checkout@v2
      - name: Publish ${{ matrix.runtime }}
        run: bin/publish --runtime ${{ matrix.runtime }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}
          path: dist/${{ matrix.runtime }}

